minimumReleaseAge: 10080
minimumReleaseAgeIgnoreMissingTime: false
trustLockfile: false
strictDepBuilds: true
allowBuilds:
  sharp: true
  unrs-resolver: true
enableGlobalVirtualStore: false
packageImportMethod: clone-or-copy
verifyDepsBeforeRun: false
optimisticRepeatInstall: false
