'use client';
import { useRef, useState } from 'react';
import { ImagePlus, ArrowUpRight, X, LoaderCircle, ShieldCheck, AlertTriangle } from 'lucide-react';
import { analyze, readImage, type Post } from '@/lib/blog/moderation';
export function Composer({ endpoint, onPublish }: { endpoint: string; onPublish: (post: Post) => void }) {
 const [text, setText] = useState(''); const [image, setImage] = useState<string>(); const [filename, setFilename] = useState(''); const [busy, setBusy] = useState(false); const [reading, setReading] = useState(false); const [error, setError] = useState(''); const [blocked, setBlocked] = useState(false); const input = useRef<HTMLInputElement>(null);
 async function select(file?: File) { if (!file) return; setReading(true); setError(''); setBlocked(false); try {setImage(await readImage(file));setFilename(file.name);} catch(e) {setError((e as Error).message);} finally {setReading(false); if(input.current) input.current.value='';} }
 async function submit(e: React.FormEvent) { e.preventDefault(); if(busy || reading || (!text.trim() && !image)) return; setBusy(true);setError('');setBlocked(false);try {const result=await analyze(text.trim(),image,endpoint);if(result.status==='blocked'){setBlocked(true);setError(`O conteúdo foi sinalizado pela moderação${result.categories.length ? `: ${result.categories.join(', ')}` : ''}. Revise o post antes de tentar novamente.`);return;}onPublish({id:crypto.randomUUID(),text:text.trim(),image,createdAt:new Date().toISOString(),analysis:result});setText('');setImage(undefined);setFilename('');}catch(e){setError((e as Error).message);}finally{setBusy(false);} }
 return <form onSubmit={submit} className="panel composer p-6 sm:p-8"><div className="mb-6 flex items-center gap-3"><div className="avatar">V</div><div><h2 className="font-semibold">Uma ideia merece espaço.</h2><p className="text-sm text-muted-foreground">O que você quer compartilhar hoje?</p></div><span className="ml-auto hidden text-xs tracking-widest text-muted-foreground sm:block">NOVO POST</span></div><label htmlFor="post-text" className="sr-only">Texto do post</label><textarea id="post-text" value={text} disabled={busy} maxLength={10000} onChange={e=>setText(e.target.value)} placeholder="Escreva algo que vale a conversa…" className="min-h-40 w-full resize-y bg-transparent text-lg leading-relaxed outline-none placeholder:text-[#77768c]"/>{image && <div className="relative mb-5 overflow-hidden rounded-xl border border-border"><img src={image} alt="Prévia da imagem selecionada" className="max-h-64 w-full bg-black/30 object-contain"/><button type="button" disabled={busy || reading} onClick={()=>{setImage(undefined);setFilename('');}} aria-label="Remover imagem" className="absolute right-3 top-3 rounded-full bg-black/80 p-2"><X size={18}/></button><p className="truncate p-3 text-sm text-muted-foreground">{filename}</p></div>}<div className="flex flex-wrap items-center justify-between gap-4 border-t border-border pt-5"><input ref={input} type="file" accept="image/png,image/jpeg" aria-label="Selecionar imagem" className="sr-only" disabled={busy || reading} onChange={e=>void select(e.target.files?.[0])}/><button type="button" className="flex items-center gap-2 rounded-lg px-1 py-2 text-sm text-muted-foreground hover:text-primary" disabled={busy || reading} onClick={()=>input.current?.click()}><ImagePlus size={19}/>{reading?'Preparando…':'Adicionar imagem'}</button><div className="flex items-center gap-4"><span className="text-xs tabular-nums text-muted-foreground">{text.length.toLocaleString('pt-BR')}/10.000</span><button className="publish-button" disabled={busy || reading || (!text.trim() && !image)} type="submit">{busy?<><LoaderCircle className="animate-spin" size={17}/> Analisando…</>:<>Publicar <ArrowUpRight size={18}/></>}</button></div></div><p className="mt-5 flex items-center gap-2 text-xs text-muted-foreground"><ShieldCheck size={14} className="shrink-0 text-primary"/>Texto e imagem passam por análise antes de aparecer no feed.</p>{error && <div role="alert" className="mt-5 rounded-xl border border-red-400/25 bg-red-400/10 p-4 text-sm text-red-200"><p className="mb-1 flex items-center gap-2 font-semibold"><AlertTriangle size={17}/>{blocked?'Publicação bloqueada':'Post não publicado'}</p>{error}</div>}</form>;
}
